services:
   mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
   web:
        build: .
        command: sh -c "sleep 10s; python3 ./app.py"
        container_name: web
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - mysql